spring.application.name=travel-planner
server.port=8082

#mysql database connection properties
#spring.datasource.url=jdbc:mysql://localhost:3306/travel_planner
#spring.datasource.username=root
#spring.datasource.password=Rittik@95174
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.datasource.url=jdbc:h2:file:~/data/travel_planner;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=etdTravelDeskJwtSecretKey1234567890ABCDEF

# auth-service URL for blacklist check
auth.service.base_url=http://localhost:8080/

# account management service URLs
account.management.service.base_url = http://localhost:8081/
account.management.service.url = api/
account.management.service.skip = false